spring:
    datasource:
        name: test
        url: jdbc:mysql://gz-cdb-1emum51s.sql.tencentcdb.com:62749/together
        username: root
        password: tongdao6
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    mapperLocations: classpath:find_friend/*.xml
    typeAliasesPackage: find_friend.po